Repository bringg/data-agents-service, pull requests merged in 2025-03, with the labels that each got.

#7 Rpc integration
  app/common/constants/index.ts
  app/common/constants/is_dev.constants.ts
  app/server.ts
  app/services/workflow/graphs/super_graph/super_graph.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/schemas/filter_schema.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/utils/get_descriptions_dict.utils.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/utils/index.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_catalog_meta_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_basic_line_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_donut_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_double_y_axis_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_line_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_multi_horizontal_reversed_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_number_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_pie_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_reversed_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_reversed_full_width_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/reports/load_tool.ts
  app/services/workflow/tools/analytic_tools/reports/meta_tool.ts
  app/services/workflow/tools/analytic_tools/reports/schemas/load_tool_schemas.ts
  config/custom-environment-variables.json5
  config/default.json5
  config/development.json5
  nodemon.json
  package-lock.json
  package.json
Labels: Review effort 3/5

#6 Added error dict, conversation messages support, code order and se...
  app/common/errors/errors_dict.ts
  app/common/errors/index.ts
  app/common/index.ts
  app/domains/chat/chat_controller.ts
  app/services/workflow/agents/human_node/human_node.ts
  app/services/workflow/agents/super_level_agents/composer_agent.ts
  app/services/workflow/agents/utils/create_team_supervisor.ts
  app/services/workflow/decorators/index.ts
  app/services/workflow/decorators/is_relevant.ts
  app/services/workflow/decorators/set_sse.ts
  app/services/workflow/graphs/analytics_sub_graph/analytics_sub_graph.ts
  app/services/workflow/graphs/super_graph/super_graph.ts
  app/services/workflow/graphs/super_graph/types/graph_state_type.ts
  app/services/workflow/prompts/semantic_router_prompt.ts
  app/services/workflow/utils/check_question_relevance.utils.ts
Labels: Review effort 3/5

#8 Bi dashboard tools
  .eslintrc.js
  app/common/constants/index.ts
  app/common/constants/is_dev.constants.ts
  app/domains/chat/chat_controller.ts
  app/server.ts
  app/services/workflow/agents/analytics_level_agents/bi_dashboards_agent.ts
  app/services/workflow/agents/analytics_level_agents/constants/analytics_members.constats.ts
  app/services/workflow/agents/analytics_level_agents/reports_agent.ts
  app/services/workflow/agents/human_node/human_node.ts
  app/services/workflow/agents/super_level_agents/composer_agent.ts
  app/services/workflow/agents/super_level_agents/documentation_agent.ts
  app/services/workflow/agents/super_level_agents/index.ts
  app/services/workflow/agents/utils/agent_state_modifier.ts
  app/services/workflow/agents/utils/create_team_supervisor.ts
  app/services/workflow/agents/utils/index.ts
  app/services/workflow/agents/utils/run_agent_node.ts
  app/services/workflow/decorators/is_relevant.ts
  app/services/workflow/decorators/set_sse.ts
  app/services/workflow/graphs/analytics_sub_graph/analytics_sub_graph.ts
  app/services/workflow/graphs/analytics_sub_graph/types/analytics_sub_graph_state_type.ts
  app/services/workflow/graphs/super_graph/constants/graph_status_description.constants.ts
  app/services/workflow/graphs/super_graph/constants/index.ts
  app/services/workflow/graphs/super_graph/super_graph.ts
  app/services/workflow/graphs/super_graph/types/graph_state_type.ts
  app/services/workflow/memory/short-term/redis-saver.ts
  app/services/workflow/memory/short-term/utils.ts
  app/services/workflow/prompts/analytics_prompts/bi_dashboards_agent_prompt.ts
  app/services/workflow/prompts/analytics_prompts/index.ts
  app/services/workflow/prompts/index.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/bi_dashboards_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/constants/index.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/constants/widget_data_tools.constants.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/index.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/schemas/filter_schema.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/schemas/index.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/utils/get_descriptions_dict.utils.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/utils/index.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_catalog_meta_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_basic_line_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_donut_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_double_y_axis_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_line_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_multi_horizontal_reversed_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_number_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_pie_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_reversed_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_reversed_full_width_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/reports/index.ts
  app/services/workflow/tools/analytic_tools/reports/load_tool.ts
  app/services/workflow/tools/analytic_tools/reports/meta_tool.ts
  app/services/workflow/tools/analytic_tools/reports/schemas/load_tool_schemas.ts
  app/services/workflow/tools/index.ts
  app/services/workflow/utils/check_question_relevance.utils.ts
  app/services/workflow/utils/llm_factory.utils.ts
  config/custom-environment-variables.json5
  nodemon.json
  package-lock.json
  package.json
Labels: Review effort 4/5

#10 Tests
  .eslintignore
  .eslintrc.js
  .gitignore
  .mocharc.js
  Jenkinsfile
  app/common/constants/is_dev.constants.ts
  app/domains/chat/chat_controller.ts
  app/http_service.ts
  app/project-root-path.ts
  app/server.ts
  app/services/workflow/agents/analytics_level_agents/bi_dashboards_agent.ts
  app/services/workflow/agents/analytics_level_agents/constants/analytics_members.constats.ts
  app/services/workflow/agents/human_node/human_node.ts
  app/services/workflow/decorators/is_relevant.ts
  app/services/workflow/graphs/analytics_sub_graph/analytics_sub_graph.ts
  app/services/workflow/graphs/super_graph/super_graph.ts
  app/services/workflow/prompts/analytics_prompts/bi_dashboards_agent_prompt.ts
  app/services/workflow/prompts/analytics_prompts/reports_builder_agent_prompt.ts
  app/services/workflow/prompts/main_supervisor_prompt.ts
  app/services/workflow/prompts/semantic_router_prompt.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/constants/widget_data_tools.constants.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/utils/get_descriptions_dict.utils.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_catalog_meta_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_number_data_tool.ts
  app/services/workflow/tools/analytic_tools/reports/schemas/load_tool_schemas.ts
  app/services/workflow/types/llm_factory.types.ts
  app/services/workflow/utils/check_question_relevance.utils.ts
  app/services/workflow/utils/llm_factory.utils.ts
  config/default.json5
  config/test.json5
  mocha-multi-reporter-config.json
  nodemon.json
  nyc.config.js
  package-lock.json
  package.json
  test/__helper__/run-server.ts
  test/__helper__/types.ts
  test/app/server.test.ts
  test/chat/api/chat-api-http-client.ts
  test/chat/api/chat-api.test.ts
  test/chat/mocks/super_graph.mock.ts
  test/constants/test.constants.ts
  test/setup/chai.ts
  test/setup/mocha-env.js
  test/setup/mocha-roothooks.ts
  test/setup/setup-test.ts
  tsconfig.build.json
  tsconfig.json
Labels: Review effort 4/5

#11 enhance analytics descriptions and supervisor prompt for clarity on t…
  app/services/workflow/agents/analytics_level_agents/constants/analytics_members.constats.ts
  app/services/workflow/prompts/analytics_prompts/analytics_supervisor_prompt.ts
Labels: Review effort 2/5

#12 refine analytics supervisor prompt for improved clarity and multi-ste…
  app/services/workflow/prompts/analytics_prompts/analytics_supervisor_prompt.ts
Labels: Review effort 2/5

#13 Jenkinsfile: remove CODECOV_TOKEN
  Jenkinsfile
Labels: Review effort 1/5

#17 Reports safeguards
  README.md
  app/server.ts
  app/services/workflow/agents/analytics_level_agents/analyzer_agent.ts
  app/services/workflow/agents/analytics_level_agents/bi_dashboards_agent.ts
  app/services/workflow/agents/analytics_level_agents/constants/analytics_members.constats.ts
  app/services/workflow/agents/analytics_level_agents/reports_agent.ts
  app/services/workflow/agents/super_level_agents/documentation_agent.ts
  app/services/workflow/agents/utils/run_agent_node.ts
  app/services/workflow/prompts/analytics_prompts/analytics_supervisor_prompt.ts
  app/services/workflow/prompts/analytics_prompts/bi_dashboards_agent_prompt.ts
  app/services/workflow/prompts/analytics_prompts/reports_builder_agent_prompt.ts
  app/services/workflow/prompts/index.ts
  app/services/workflow/prompts/super_prompts/composer_agent_prompt.ts
  app/services/workflow/prompts/super_prompts/documentation_agent_prompt.ts
  app/services/workflow/prompts/super_prompts/index.ts
  app/services/workflow/prompts/super_prompts/main_supervisor_prompt.ts
  app/services/workflow/prompts/super_prompts/semantic_router_prompt.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/schemas/filter_schema.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_basic_line_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_donut_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_double_y_axis_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_line_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_multi_horizontal_reversed_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_number_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_pie_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_reversed_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/bi_dashboards/widget_type_reversed_full_width_bar_data_tool.ts
  app/services/workflow/tools/analytic_tools/reports/constants/cube_constants.ts
  app/services/workflow/tools/analytic_tools/reports/load_tool.ts
  app/services/workflow/tools/analytic_tools/reports/schemas/load_tool_schemas.ts
  app/services/workflow/tools/analytic_tools/reports/utils/cube_utils.ts
  app/services/workflow/tools/analytic_tools/reports/utils/http_utils.ts
  app/services/workflow/tools/analytic_tools/reports/utils/index.ts
  app/services/workflow/tools/analytic_tools/reports/utils/rpc_utils.ts
  app/services/workflow/tools/analytic_tools/reports/utils/validation_utils.ts
  app/services/workflow/tools/super_tools/documentation/index.ts
  app/services/workflow/tools/super_tools/documentation/rag_fetch_tool.ts
  app/services/workflow/tools/super_tools/index.ts
  app/services/workflow/tools/tools.const.ts
  config/default.json5
  nyc.config.js
Labels: Review effort 3/5
